### ISSUE TITLE
[BUG] @mastra/e2b: sandbox creation fails with "Sandbox.betaCreate is not a function" on e2b SDK >= 2.24.0

### ISSUE THREAD

**Issue by yashsharma999** [mastra-ai/mastra#17258]
### Describe the Bug

 `@mastra/e2b` calls the experimental `Sandbox.betaCreate()` method from the `e2b` SDK. That method was **removed in `e2b@2.24.0`** (promoted to the stable `Sandbox.create()`, with `autoPause` replaced by `lifecycle: { onTimeout: 'pause' }`).

 Because `workspaces/e2b/package.json` declares the dependency loosely as `"e2b": "^2.14.1"`, any fresh install resolves a current SDK (2.24.0–2.27.0) that no longer has `betaCreate`. As soon as the sandbox has to be **created**, it throws and `execute_command` returns exit `-1`:

```
  Error: Sandbox.betaCreate is not a function
```

### Steps To Reproduce

1. Create a Mastra project and add `@mastra/e2b` (fresh install → `e2b` resolves to ≥ 2.24.0, currently 2.27.0).
2. Configure a workspace with an E2B sandbox:

     ```ts
     import { Workspace, LocalFilesystem } from '@mastra/core/workspace';
     import { E2BSandbox } from '@mastra/e2b';

     export const workspace = new Workspace({
       filesystem: new LocalFilesystem({ basePath: './workspace' }),
       sandbox: new E2BSandbox({ id: 'repro' }),
     });
     ```
3. Attach the workspace to an agent, run `mastra dev`, and ask the agent to run a shell command (e.g. "run `pwd` in the sandbox")
4. `execute_command` fails with `Error: Sandbox.betaCreate is not a function`.

### Link to Minimal Reproducible Example

https://github.com/yashsharma999/mastra-bug-reproduction

### Expected Behavior

Sandbox creation should succeed on current `e2b` SDK versions, and `execute_command` should run shell commands. The auto-pause-on-timeout behaviour (previously `autoPause: true`) should be preserved.

### Environment Information

```block
System: macOS (Darwin 25.5.0)
  Node:   v25.9.0

  npmPackages:
    @mastra/e2b:   0.3.1 (latest)
    @mastra/core:  1.37.0
    @mastra/s3:    0.5.1
    mastra (CLI):  1.10.1

  Resolved transitive:
    e2b: 2.27.0   (fails on any e2b >= 2.24.0; works on <= 2.23.0)
```

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

**Comment by daneatmastra** [comment]
Thank you for reporting this issue! We have labeled it for trio-tnt and we will look into it as soon as possible.

If you're experiencing an error, please provide a [minimal reproducible example](https://github.com/mastra-ai/mastra/blob/main/CONTRIBUTING.md#minimal-reproduction) whenever possible to help us resolve it quickly.
