### ISSUE TITLE
[BUG] @mastra/server dual-auth calls this.mastra.getStudio() unguarded → "TypeError: this.mastra.getStudio is not a function"

### ISSUE THREAD

**Issue by meirLixen** [mastra-ai/mastra#18073]
### What happened

A deployed Mastra app crashes on every request with:

```
TypeError: this.mastra.getStudio is not a function
```

### Root cause

The dual-auth request router added in #17722 calls `this.mastra.getStudio()`
**unguarded** in several places in
`packages/server/src/server/server-adapter/index.ts` (current `main`):

- `getEffectiveAuthConfig()` — line 281:
  ```ts
  const studioAuth = this.mastra.getStudio()?.auth;
  ```
  The optional chaining is on `.auth`, **not** on the `getStudio()` call itself.
- `getEffectiveRBACProvider()` — line 356:
  ```ts
  return this.mastra.getStudio()?.rbac ?? this.mastra.getServer()?.rbac;
  ```
- `getEffectiveFGAProvider()` — line 365:
  ```ts
  return this.mastra.getStudio()?.fga ?? this.mastra.getServer()?.fga;
  ```

`getEffectiveAuthConfig()` runs in the per-request auth path, so if the running
`@mastra/core` does not expose `getStudio`, **every request throws**.

`Mastra.getStudio()` was only added to `@mastra/core` in **1.42.0** (absent in
1.41.0 and in 1.42.0-alpha.2; first present in 1.42.0-alpha.4). `@mastra/server`
1.42.0 therefore hard-requires `@mastra/core >= 1.42.0` at runtime, but nothing
enforces that the *bundled/resolved* core meets it.

Note the same file already guards the call correctly elsewhere
(lines 512 and 674 use `this.mastra.getStudio?.()`), so the unguarded sites are
simply inconsistent oversights.

### How it surfaces in deploys

`@mastra/deployer` writes the generated `.mastra/output/package.json` using the
project's *resolved* `@mastra/core` version (read from the resolved package's own
`package.json`, falling back to `latest`). If the project's lockfile / transitive
resolution pins an older `@mastra/core` (< 1.42.0), the bundled core lacks
`getStudio` and the server crashes at runtime even though dev worked.

### Expected

The server should not hard-crash when `getStudio` is unavailable; it should
degrade to server-only auth (the same way the already-guarded call sites do).

### Actual

`TypeError: this.mastra.getStudio is not a function` on every request.

### Suggested fix (one line each)

Guard the call the same way the rest of the file already does — add `?.` on
`getStudio` itself:

```ts
// line 281
const studioAuth = this.mastra.getStudio?.()?.auth;
// line 356
return this.mastra.getStudio?.()?.rbac ?? this.mastra.getServer()?.rbac;
// line 365
return this.mastra.getStudio?.()?.fga ?? this.mastra.getServer()?.fga;
```

Optionally, also add a runtime peer-dependency check so a too-old `@mastra/core`
produces a clear error instead of a cryptic `TypeError`.

### Affected versions

- `@mastra/server` 1.42.0 (the `server-adapter` dual-auth path; introduced in #17722).
- Triggered whenever the resolved/bundled `@mastra/core` is < 1.42.0.
- Still present on `main` as of this report.
- Note: `@mastra/server` 2.0.x removed the `server-adapter` path entirely, so the
  2.x line is not affected — this targets the current 1.42.x release line.

### Workaround

Pin `@mastra/core`, `@mastra/server`, and `@mastra/deployer` to a consistent
version (e.g. all to 1.42.0, or all to the last pre-#17722 release) so the
bundled core matches the server.

**Comment by daneatmastra** [comment]
Thank you for reporting this issue! We have labeled it for the team and we will look into it as soon as possible.

If you're experiencing an error, please provide a [minimal reproducible example](https://github.com/mastra-ai/mastra/blob/main/CONTRIBUTING.md#minimal-reproduction) whenever possible to help us resolve it quickly.

**Comment by Aayush-engineer** [comment]
Looking into this the fix is straightforward, I'll have a PR up shortly.

**Comment by Aayush-engineer** [comment]
The three unguarded getStudio() calls in server-adapter/index.ts (getEffectiveAuthConfig, getEffectiveRBACProvider, getEffectiveFGAProvider) were missing ?. before (), causing a hard crash when the resolved @mastra/core is < 1.42.0. Fixed by adding optional chaining getStudio?.() on all three sites to match the pattern already used elsewhere in the file. PR: #18075
