### ISSUE TITLE
[DISCORD:1423431095889821778] Updated to Mastra 0.19 everything breaks

### ISSUE THREAD

**Issue by wardpeet** [mastra-ai/mastra#8452]
This issue was created from Discord post: https://discord.com/channels/1309558646228779139/1423431095889821778

This is starting to feel like a reoccuring pattern. I am avoiding updating mastra now because every-time a new release is pushed it feels like it is not tested, and it introduces new issues that break our existing workflows.

There is no context here, this is just the output we are getting. Worked fine in 0.16.0, and now its broken. Version 0.17.0 and 0.18.0 were also broken so we omited updating to thoes versions, but now we are missing out on core features because they get added in future versions, that have regressive behaviors.

```
Error executing step: Error: Date cannot be represented in JSON Schema
    at JSONSchemaGenerator.process (/query/node_modules/zod/v4/core/to-json-schema.cjs:194:35)
    at /query/node_modules/zod/v4/core/to-json-schema.cjs:255:72
    at ...
ERROR from StructuredOutputProcessor: [StructuredOutputProcessor] Processing failed: result.getFullOutput is not a function
Error executing model claude-sonnet-4-5-20250929, attempt 1==== Error: Date cannot be represented in JSON Schema
    at JSONSchemaGenerator.process (/query/node_modules/zod/v4/core/to-json-schema.cjs:194:35)
    at /query/node_modules/zod/v4/core/to-json-schema.cjs:255:72
    at ...
Error executing step llm-execution: TypeError: Cannot destructure property 'outputStream' of '(intermediate value)' as it is undefined.
```

**Comment by DanielSLew** [comment]
Closing this as we can continue discussion on discord if more issues arise
