### ISSUE TITLE
[BUG] Harness v1 ask_user/submit_plan tools read runId/traceId from non-existent context fields (tsc build fails)

### ISSUE THREAD

**Issue by praveenpke** [mastra-ai/mastra#18126]
## Describe the Bug

The Harness v1 built-in tools `ask_user` and `submit_plan` (`packages/core/src/harness/v1/tools.ts`) read `runId` and `traceId` from fields that don't exist on their context types:

```ts
runId: context.agent?.runId ?? context.workflow?.runId ?? null,
traceId: context.traceId ?? null,
```

- `AgentToolExecutionContext` has no `runId` property.
- `ToolExecutionContext` has no top-level `traceId` property.

So `tsc` fails with 4 errors when building `@mastra/core`:

```
src/harness/v1/tools.ts(219,35): error TS2339: Property 'runId' does not exist on type 'AgentToolExecutionContext<unknown, unknown>'.
src/harness/v1/tools.ts(220,30): error TS2339: Property 'traceId' does not exist on type 'ToolExecutionContext<unknown, unknown, unknown>'.
src/harness/v1/tools.ts(240,35): error TS2339: Property 'runId' does not exist on type 'AgentToolExecutionContext<unknown, unknown>'.
src/harness/v1/tools.ts(241,30): error TS2339: Property 'traceId' does not exist on type 'ToolExecutionContext<unknown, unknown, unknown>'.
```

This is **platform-independent** (fails on macOS/Linux/Windows). It isn't caught by CI because the test suite type-checks via Vitest (esbuild transpile, no `tsc` emit) — the full `tsc` `.d.ts` build only runs at publish time. At runtime esbuild strips the types, so `context.agent?.runId` / `context.traceId` silently evaluate to `undefined`, meaning these fields were effectively **always `null` and never populated**.

Likely introduced in #17534 ("Refine Harness v1 session records and tools").

## Steps To Reproduce

1. Clone the monorepo and install deps (`pnpm install`).
2. Run `pnpm --filter @mastra/core exec tsc --noEmit -p tsconfig.build.json` (or `pnpm build:core`).
3. Observe the 4 `TS2339` errors in `src/harness/v1/tools.ts` shown above.

## Link to Minimal Reproducible Example

Reproduces directly in this repository — no separate project is needed. The `tsc` build of `@mastra/core` on any platform surfaces the errors above (`pnpm --filter @mastra/core exec tsc --noEmit -p tsconfig.build.json`).

## Expected vs Actual

- **Expected:** `@mastra/core` builds cleanly under `tsc`; the pending-item `runId` / `traceId` reflect the active run.
- **Actual:** `tsc` fails with 4 `TS2339` errors; at runtime the values were always `null`.

## Suggested fix

The harness session already tracks the active run via the public `getCurrentRunId()` / `getCurrentTraceId()` getters. Sourcing the values from the session fixes the type error and correctly populates them (proposed in a PR).

## Environment

- `@mastra/core` (monorepo build), TypeScript 6.0.3, all platforms.

**Comment by daneatmastra** [comment]
Thank you for reporting this issue! We have labeled it for trio-tb and we will look into it as soon as possible.

If you're experiencing an error, please provide a [minimal reproducible example](https://github.com/mastra-ai/mastra/blob/main/CONTRIBUTING.md#minimal-reproduction) whenever possible to help us resolve it quickly.

**Comment by wardpeet** [comment]
We'v removed v1 for now, moving everything to v0
