### PR TITLE
fix(e2b): use stable Sandbox.create() for e2b SDK >= 2.24.0

### LINKED ISSUE #17258: [BUG] @mastra/e2b: sandbox creation fails with "Sandbox.betaCreate is not a function" on e2b SDK >= 2.24.0
### Describe the Bug

 `@mastra/e2b` calls the experimental `Sandbox.betaCreate()` method from the `e2b` SDK. That method was **removed in `e2b@2.24.0`** (promoted to the stable `Sandbox.create()`, with `autoPause` replaced by `lifecycle: { onTimeout: 'pause' }`).

 Because `workspaces/e2b/package.json` declares the dependency loosely as `"e2b": "^2.14.1"`, any fresh install resolves a current SDK (2.24.0–2.27.0) that no longer has `betaCreate`. As soon as the sandbox has to be **created**, it throws and `execute_command` returns exit `-1`:

```
  Error: Sandbox.betaCreate is not a function
```

### Steps To Reproduce

1. Create a Mastra project and add `@mastra/e2b` (fresh install → `e2b` resolves to ≥ 2.24.0, currently 2.27.0).
2. Configure a workspace with an E2B sandbox:

     ```ts
     import { Workspace, LocalFilesystem } from '@mastra/core/workspace';
     import { E2BSandbox } from '@mastra/e2b';

     export const workspace = new Workspace({
       filesystem: new LocalFilesystem({ basePath: './workspace' }),
       sandbox: new E2BSandbox({ id: 'repro' }),
     });
     ```
3. Attach the workspace to an agent, run `mastra dev`, and ask the agent to run a shell command (e.g. "run `pwd` in the sandbox")
4. `execute_command` fails with `Error: Sandbox.betaCreate is not a function`.

### Link to Minimal Reproducible Example

https://github.com/yashsharma999/mastra-bug-reproduction

### Expected Behavior

Sandbox creation should succeed on current `e2b` SDK versions, and `execute_command` should run shell commands. The auto-pause-on-timeout behaviour (previously `autoPause: true`) should be preserved.

### Environment Information

```block
System: macOS (Darwin 25.5.0)
  Node:   v25.9.0

  npmPackages:
    @mastra/e2b:   0.3.1 (latest)
    @mastra/core:  1.37.0
    @mastra/s3:    0.5.1
    mastra (CLI):  1.10.1

  Resolved transitive:
    e2b: 2.27.0   (fails on any e2b >= 2.24.0; works on <= 2.23.0)
```

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by SaarthurR**
## Summary

- Replace the removed `Sandbox.betaCreate()` with the stable `Sandbox.create()` and swap the deprecated `autoPause: true` option for `lifecycle: { onTimeout: 'pause' }`. In e2b SDK 2.24.0 `betaCreate()` was promoted to `create()` and removed, so sandbox creation crashed with "Sandbox.betaCreate is not a function".
- Bump the `e2b` dependency range to `^2.24.0` so fresh installs resolve a compatible SDK.

## Test plan

- `pnpm --filter ./workspaces/e2b test:unit`

Closes #17258

## ELI5

This PR fixes a crash that happens when using the newer e2b library. The code was trying to use an old function that doesn't exist anymore (`Sandbox.betaCreate`), so we updated it to use the new official function (`Sandbox.create`). We also updated how we tell the sandbox to pause when it times out, so the code works the same way as before but with the new library.

## Changes

Updated the `@mastra/e2b` package to work with e2b SDK v2.24.0 and later by migrating from the deprecated `Sandbox.betaCreate()` API to the stable `Sandbox.create()` API, and replacing the deprecated `autoPause: true` option with the new `lifecycle: { onTimeout: 'pause' }` configuration.

### Files Changed

- **workspaces/e2b/package.json**: Updated e2b dependency from `^2.14.1` to `^2.24.0`
- **workspaces/e2b/src/sandbox/index.ts**: Migrated sandbox creation logic from `Sandbox.betaCreate()` to `Sandbox.create()`, updated timeout configuration to use `lifecycle: { onTimeout: 'pause' }`, and refactored creation options into a reusable `sandboxCreateOpts` object
- **workspaces/e2b/src/sandbox/index.test.ts**: Updated all test mocks and assertions to target `Sandbox.create` instead of `Sandbox.betaCreate`, including template rebuild retry logic, custom template handling, connection options forwarding, and error path tests
- **.changeset/seven-mirrors-jump.md**: Added changeset entry documenting the patch-level fix

## Testing

Unit tests for the e2b workspace have been updated to verify:
- Sandbox creation with the new `Sandbox.create()` API
- Correct timeout behavior via `lifecycle: { onTimeout: 'pause' }`
- Template preparation and rebuild edge cases
- Custom template and connection option forwarding
- Retry logic on dead sandbox scenarios

Run tests via: `pnpm --filter ./workspaces/e2b test:unit`

## Related Issue

Closes `#17258` - Fixes "Sandbox.betaCreate is not a function" error that occurred with e2b SDK >= 2.24.0

[Review Change Stack](https://app.coderabbit.ai/change-stack/mastra-ai/mastra/pull/17329?utm_source=github_walkthrough&utm_medium=github&utm_campaign=change_stack)

### CODE REVIEW

**Comment by abhiaiyer91** [comment]
A PR already exists for this https://github.com/mastra-ai/mastra/pull/17261
