### ISSUE TITLE
[BUG] Scheduler crashes on Cloudflare Workers: setInterval(...).unref is not a function (regression from #18713)

### ISSUE THREAD

**Issue by owk-owk130** [mastra-ai/mastra#19462]
## Describe the bug

On Cloudflare Workers (workerd), calling `.generate()` on an `Agent` that is not registered to a `Mastra` instance throws:

```
TypeError: this.#intervalHandle.unref is not a function
```

The unregistered agent lazily creates its fallback ephemeral Mastra (`InMemoryStore`), which starts workers on first use. The Scheduler then calls `setInterval(...).unref()` — but workerd's `setInterval` returns a **number**, not a Node.js `Timeout` object, so `.unref` does not exist.

## Root cause

PR #18713 added `.unref()` to the scheduler interval so Node.js scripts can exit naturally. The fix is correct for Node.js, but the call is unguarded:

```ts
// packages/core/src/workflows/scheduler/scheduler.ts
this.#intervalHandle = setInterval(() => { ... }, this.#config.tickIntervalMs);
this.#intervalHandle.unref();   // ← crashes on workerd (setInterval returns a number)
```

Other call sites in the same codebase already guard this pattern:

```ts
this.intervalId.unref?.();
if (this.cleanupIntervalId.unref) { this.cleanupIntervalId.unref(); }
```

## Impact

- Any bare `new Agent(...).generate()` on Workers crashes (documented as a supported pattern for scripts/tests).
- The documented `MastraAgentRelevanceScorer` rerank pattern is completely broken on Workers, since it creates an unregistered internal Agent per instance — every `rerankWithScorer` call fails.
- Reproduced on `@mastra/core` 1.49.0. Confirmed still present in 1.50.1 (latest stable) and 1.51.0-alpha.8.

## Steps to reproduce

1. `wrangler dev` (or deploy) a Worker with `@mastra/core` >= 1.49.0
2. Call `generate()` on an Agent not attached to any Mastra instance (or use `MastraAgentRelevanceScorer` via `rerankWithScorer`)
3. Observe the `TypeError`

## Suggested fix

```ts
this.#intervalHandle.unref?.();
```

This fully preserves the Node.js process-exit fix from #18713 — on workerd the numeric handle simply skips the call.

## Workaround

Register agents to a Mastra instance with workers disabled before calling `generate()`:

```ts
new Mastra({ logger: false, workers: false, agents: { myAgent } });
```

## Environment

- `@mastra/core`: 1.49.0 (also 1.50.1, 1.51.0-alpha.8)
- Runtime: Cloudflare Workers (workerd), `compatibility_date: 2025-12-02`, `nodejs_compat` enabled

**Comment by daneatmastra** [comment]
Thank you for reporting this issue! We have labeled it for trio-wp and we will look into it as soon as possible.

If you're experiencing an error, please provide a [minimal reproducible example](https://github.com/mastra-ai/mastra/blob/main/CONTRIBUTING.md#minimal-reproduction) whenever possible to help us resolve it quickly.
