### ISSUE TITLE
mastracode/sdk unit tests never run in CI (bad vitest glob + red suite on main)

### ISSUE THREAD

**Issue by TylerBarnes** [mastra-ai/mastra#24219]
`mastracode/sdk` is not in the root vitest workspace, so its unit suite never runs in CI. It also has failures on `main` that need fixing before it can be registered.

## The wiring gap

The root `vitest.config.ts` scans `PROJECT_GLOBS` for `mastracode/vitest.config.ts`:

```
'mastracode/vitest.config.ts',
```

That path does not exist. The real configs live one level deeper, at `mastracode/*/vitest.config.ts` (`sdk`, `tui`, `web`, `factory`, `factory-ui`, `mastra-factory`). So the project filter used by the unit jobs never matches:

```
$ npx vitest list --project 'unit:mastracode-core'
Error: No projects matched the filter "unit:mastracode-core".
```

`.github/workflows/test-suite.yml` runs both the sharded and affected jobs with `--project 'unit:*'`, so neither can reach `unit:mastracode-core`. `mastracode/sdk/vitest.config.ts` declares that project name, and the root config expands nested projects with `root: './mastracode/sdk'`, so adding `'mastracode/sdk/vitest.config.ts'` to `PROJECT_GLOBS` is all the discovery needs.

The only mastracode CI job today is `Mastra Code E2E` (`.github/workflows/mastracode-e2e.yml`), which runs the TUI E2E suite and no SDK unit tests.

## Why it cannot be registered yet

The SDK suite is not green on `main`. On a clean `origin/main` checkout with a full build (`pnpm build:mastracode`, required so workspace imports resolve):

```
$ cd mastracode/sdk && npx vitest run
 Test Files  1 failed | 118 passed | 1 skipped (120)
      Tests  1 failed | 1702 passed | 2 skipped (1705)
```

The failure is `src/index.test.ts` > `createMastraCode startup performance` > `does not wait for background gateway sync before returning storage warnings`: `Error: Test timed out in 5000ms`. It takes about 7.4s and passes with `--testTimeout=30000`. The test awaits a dynamic `import('./index.js')` of a large module graph, so the default 5s budget is tight rather than the assertion being wrong.

`pnpm --filter ./mastracode/sdk check` also fails on `main`, independently of the above:

```
src/tools/workflows/save-workflow.ts:19:3 - error TS2345
  The types of '_zod.version.minor' are incompatible between these types.
    Type '6' is not assignable to type '4'.
```

That looks like a zod version skew (the SDK resolves zod 4.4.3 while the root resolves 4.6.5).

## Suggested approach

Raise or remove the timeout on the startup-performance test, resolve the zod skew so `check` is clean, then add `'mastracode/sdk/vitest.config.ts'` to `PROJECT_GLOBS` and let the unit jobs pick it up. The SDK config pins `maxConcurrency: 1` and `fileParallelism: false`, so worth watching CI time once it runs.

Spotted while fixing two silently-failing cross-process signal tests in #24217. The detector blind spot that hid those tests is filed separately as #24218.

**Comment by TheIsrael1** [comment]
|                |                                                                                                           |
| -------------- | --------------------------------------------------------------------------------------------------------- |
| **Type**       | bug — MastraCode SDK unit tests are omitted from root Vitest discovery and therefore never run in CI.   |
| **Route**      | Pending                                                                                                   |
| **Severity**   | Pending                                                                                                   |
| **Confidence** | Pending                                                                                                   |
| **Next step**  | Pending                                                                                                   |
