### PR TITLE
fix(core): stop @mastra/ai-sdk/ui crashing in browser bundles

### PR DESCRIPTION
**Pull request by roaminro**
Importing `toAISdkMessages` from `@mastra/ai-sdk/ui` in a browser app started crashing with `Uncaught TypeError: createRequire is not a function` after the tsup-to-tsdown build migration (first shipped in `@mastra/core@1.54.0`). The vendored AI SDK v4's Node-only test tooling was bundled with its main entries, which hoisted eager `createRequire(import.meta.url)` initialization into a chunk loaded by `@mastra/core/agent/message-list`.

```ts
import { toAISdkMessages } from '@mastra/ai-sdk/ui';
```

This separates the vendored `src/test.ts` build from the browser-reachable main entries. The main build owns output cleanup, the isolated test build appends its output, and declaration processing runs only after both builds succeed. Shared tsdown options prevent the two builds from drifting.

The regression test bundles the source UI entry with Rspack for a web target without Node fallbacks, executes it in a VM containing only the required web globals, and verifies message conversion. It does not depend on ignored or stale `@mastra/ai-sdk` build output.

## Test plan

- Browser bundle regression test fails with the reported `createRequire` error before the build fix and passes after it, including without a prebuilt `@mastra/ai-sdk/dist` directory.
- Vendored AI SDK v4 build produces all JavaScript and declaration entries; `createRequire` remains confined to the Node-only `test.js` entry.
- Browser bundle and message-conversion tests pass (13 tests).
- Core message-list suite passes (43 files, 554 tests, 2 skipped).
- Focused builds, typechecks, formatting, and lint checks pass.

Co-Authored-By: Mastra Code (anthropic/claude-fable-5) <noreply@mastra.ai>

## ELI5

The browser was loading Node.js-only code and crashing. This PR keeps that code out of browser bundles and adds a test to prevent the problem from returning.

## Changes

- Built `src/test.ts` with a separate tsdown configuration.
- Shared typed tsdown settings across production and test builds.
- Added declaration-file processing and build finalization.
- Documented possible duplicate modules from split build graphs.
- Added an Rspack browser-bundle regression test for `toAISdkMessages`.
- Added `@rspack/core` and `tsx` development dependencies.
- Added patch changesets for `@mastra/ai-sdk` and `@mastra/core`.
- Reformatted an unrelated `MastraMemory` type assertion without changing behavior.

## Validation

- Browser regression test
- Core message-list tests
- Build
- Typecheck
- Formatting
- Lint

### CODE REVIEW

File: .changeset/bold-zoos-fail.md [hunk 1]
```diff
@@ -0,0 +1,6 @@
+---
+'@mastra/ai-sdk': patch
+'@mastra/core': patch
+---
+
+Fixed `@mastra/ai-sdk/ui` crashing in browser bundles with `TypeError: createRequire is not a function`. Importing `toAISdkMessages` (or anything reaching `@mastra/core/agent/message-list`) eagerly executed Node-only `createRequire` interop from a shared build chunk; the Node-only vendored test tooling is now built separately so browser-consumable chunks stay free of Node built-ins.
```
[the remark this answers is not in the document]
Comment (roaminro) [reply .changeset/bold-zoos-fail.md]: AI says: Updated the changeset in 77bf901d61 to describe the user-visible `toAISdkMessages` fix while preserving the searchable `TypeError: createRequire is not a function` symptom. @coderabbitai

Mastra Code

File: client-sdks/ai-sdk/src/__tests__/browser-bundle.test.ts [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+  const stats = await new Promise<Stats>((resolve, reject) => {
+    compiler.run((error, result) => {
+      if (error) reject(error);
+      else if (!result) reject(new Error('Rspack did not return build stats'));
+      else resolve(result);
+    });
+  });
+  await new Promise<void>((resolve, reject) => {
+    compiler.close(error => (error ? reject(error) : resolve()));
+  });
```
[the remark this answers is not in the document]
Comment (roaminro) [reply client-sdks/ai-sdk/src/__tests__/browser-bundle.test.ts]: AI says: Confirmed this is addressed in 43f8bf1aa8. `compiler.run()` is wrapped in `try/finally`, and `compiler.close()` runs for both successful and rejected builds. @coderabbitai

Mastra Code

**Comment by roaminro** [comment]
AI says: Addressed the remaining @coderabbitai review notes:

- `d02b00589d` validates shared options with tsdown 0.22.9’s exported `UserConfig` type and removes the per-field literal assertions.
- `390c990711` documents the intentional duplicate-module tradeoff of the isolated build graphs.

Both changes pass the vendored package typecheck and build.

Mastra Code

**Review by abhiaiyer91 — APPROVED** [review]

**Comment by roaminro** [comment]
The PR merged before the final changed-test and generated-output CI fixes landed. I opened #20767 with those two follow-ups: the split-build invariant now runs under Core's discovered Vitest project, and the generated client route types are refreshed so build-output validation stays clean.
