### ISSUE TITLE
[BUG] Workspace read_file throws for unknown .constructor and .__proto__ extensions

### ISSUE THREAD

**Issue by yyydddkkk** [mastra-ai/mastra#23957]
# [BUG] Workspace read_file throws for unknown .constructor and .__proto__ extensions

## Describe the Bug

Local workspace text files named `file.constructor` or `file.__proto__` cannot be read with the default read_file tool. It throws `TypeError: mimeType.startsWith is not a function` instead of treating these unknown extensions as `application/octet-stream` and reading their text.

The MIME table lookup in [fs-utils.ts](https://github.com/mastra-ai/mastra/blob/3fc8c2d35f724c3648150b29e50cf61a9360b274/packages/core/src/workspace/filesystem/fs-utils.ts#L205) reads inherited object properties. `.constructor` returns the Object constructor and `.__proto__` returns Object.prototype. These values reach the MIME string checks in read_file. This is a narrow filename edge case; ordinary text and unknown extensions work.

## Steps To Reproduce

1. Check out Mastra commit `3fc8c2d35f724c3648150b29e50cf61a9360b274`.
2. Run `pnpm install --frozen-lockfile --filter @mastra/core...` and `pnpm build:core`.
3. Run the accompanying `repro.mjs` with the built workspace entry point:

```sh
node repro.mjs /path/to/mastra/packages/core/dist/workspace/index.js
```

The script creates and removes its own temporary files and uses the exported Workspace, LocalFilesystem and createWorkspaceTools APIs. No model, credentials, network service or mocks are involved.

Actual output:

```text
control.txt: OK (text/plain)
unknown.xyz: OK (application/octet-stream)
file.constructor: mimeType.startsWith is not a function; typeof mimeType = function
file.__proto__: mimeType.startsWith is not a function; typeof mimeType = object
AssertionError: Every text file should remain readable regardless of its unknown extension
```

## Link to Minimal Reproducible Example

https://gist.github.com/yyydddkkk/b0832211ecb7206b64672d56fab360e7

## Expected Behavior

Unknown extensions return the fallback MIME string. The read_file tool reads these text files just as it reads `unknown.xyz`.

## Environment Information

- Checked: 2026-09-15
- Ubuntu/Linux, Node.js v24.21.0, pnpm 11.21.0
- Current main at the commit above; @mastra/core manifest version 1.67.0-alpha.4
- No browser, LLM or external storage involved
- Published npm versions have not been tested

## Proposed Fix and Verification

Restrict the MIME table lookup to its own properties. A local one-line fix preserves the existing mappings and fallback. Five added regression cases fail before the fix; all 127 tests across fs-utils and read-file pass afterward. Core typechecking, targeted ESLint/oxlint and formatting pass. The existing test setup is used without mocks for filesystem operations.

## Verification

- [x] Searched open and closed issues and PRs for getMimeType, MIME_TYPES, mime constructor, mime prototype and the exact error. No matching report or fix found as of 2026-09-15. #17870 adds existing helper coverage; #16570 introduced the relevant read_file MIME behavior.
- [x] Included a deterministic reproduction and normal controls.

This report requests maintainer triage before opening a PR, in accordance with the bug report template.

**Comment by TheIsrael1** [comment]
|                |                                                                                                                                                                 |
| -------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Type**       | bug — `getMimeType` indexes the MIME table with the raw extension, so `.constructor`/`.__proto__` filenames resolve to inherited `Object.prototype` members     |
| **Route**      | Plan fix                                                                                                                                                        |
| **Severity**   | 🟢 low — real crash but only for pathological filenames; ordinary files unaffected                                                                              |
| **Confidence** | high — root cause reproduced independently and traced end to end                                                                                                |
| **Effort**     | low — one-line guard in a single helper plus regression cases                                                                                                   |
| **Impact**     | low — narrow filename edge case with no practical exposure in normal use                                                                                        |
| **Next step**  | Plan a fix restricting the MIME lookup to own properties (e.g. `Object.hasOwn`, or a null-prototype table) and add regression tests                             |

### Understanding

`getMimeType` in `packages/core/src/workspace/filesystem/fs-utils.ts:205-208` does:

```ts
const ext = path.extname(filename).slice(1).toLowerCase();
return MIME_TYPES[ext] ?? 'application/octet-stream';
```

`MIME_TYPES` is a plain object literal (line 78), so it inherits `Object.prototype`. When `ext` is `constructor`, `MIME_TYPES['constructor']` returns the `Object` constructor **function**; when `ext` is `__proto__`, it returns `Object.prototype` (an **object**). Neither is `null`/`undefined`, so the `?? 'application/octet-stream'` fallback never fires and a non-string leaks out.

That value flows through `LocalFilesystem.stat` → `getMimeType` (line 334) into the read_file tool. `isTextLikeMimeType` in `packages/core/src/workspace/tools/read-file.ts:38-46` calls `mimeType.startsWith('text/')`, which throws `TypeError: mimeType.startsWith is not a function` for a function/object value. Reproduced the exact mechanism: `xyz` → string (ok), `constructor` → function (no `startsWith`), `__proto__` → object (no `startsWith`).

Affected surface: any workspace file whose final extension is an inherited `Object.prototype` key (`constructor`, `__proto__`, `hasOwnProperty`, `toString`, `valueOf`, etc.). Ordinary and unknown extensions are unaffected.

Suggested direction: constrain the lookup to own properties — `Object.hasOwn(MIME_TYPES, ext) ? MIME_TYPES[ext] : 'application/octet-stream'`, or declare `MIME_TYPES` with `Object.create(null)`. This preserves all existing mappings and the fallback. The reporter proposes the same one-line fix with five regression cases. Domain: direct `@mastra/core` bug.

Related history: the MIME/read_file behavior was introduced in #16570; #17870 added helper coverage. No duplicate or prior report found (search for getMimeType/MIME/octet-stream returned only this issue).

### Assumptions

- Fix belongs in the `getMimeType` helper rather than in `isTextLikeMimeType`, since the helper is the source of the malformed non-string value and other callers (e.g. `stat`) also consume it.
- Preferred `Object.hasOwn`/null-prototype approach over string-coercing the result, to keep the MIME contract (always a string) intact at the source.
- Severity/impact rated low: no evidence of real-world filenames like `file.constructor`; treated as a robustness/correctness fix, not a user-facing regression.

### Open questions

None requiring a human — scope, cause, and fix direction are unambiguous.

### Reproduction

Root-cause mechanism reproduced directly with Node:

```
node -e "const M=Object.assign({},{txt:'text/plain'}); const l=e=>M[e]??'application/octet-stream'; for(const e of ['xyz','constructor','__proto__']){const v=l(e); console.log(e, typeof v, typeof v.startsWith==='function')}"
# xyz => string true
# constructor => function false   (Object.prototype.constructor)
# __proto__ => object false        (Object.prototype)
```

Matches the reporter's `repro.mjs` output (`mimeType.startsWith is not a function`). Full end-to-end repro via the reporter's gist against a built `@mastra/core` workspace entry point is documented in the issue.
